
const facultyFeatures = [
    {heading:'Effortless Classroom Creation:' , text: 'Easily set up virtual classrooms for your courses.'},
    {heading:'Centralized Content Sharing:' , text: 'Upload and organize all your course materials, including documents, presentations, and multimedia, in one accessible location for your students.'},
    {heading:'Seamless Attendance Tracking:' , text: 'Generate unique QR codes for each class session, allowing students to quickly and accurately mark their attendance. Monitor attendance records with ease.'},
    {heading:'Simplified Student Management:' , text: 'Easily manage students enrolled in your classrooms.'},
    {heading:'Direct Student Communication:' , text: 'Manage and respond to chat requests from students, providing timely support and clarification.'},
    {heading:'Structured Communication:' , text: 'Set specific schedules for chatting with students, ensuring focused and organized communication.'},
    {heading:'Real-time Interaction:' , text: 'Engage in direct chat with students for questions, discussions, and support within the platform.'},
    {heading:'Organized Routine Access:' , text: 'Provide students with clear visibility of their class schedules and routines.'},
]

const studentFeatures = [
    {
      "heading": "Easy Classroom Enrollment",
      "text": "Join classrooms created by your faculty with a simple process."
    },
    {
      "heading": "Hassle-Free Attendance Marking",
      "text": "Mark your attendance quickly and accurately by scanning the QR code generated by your faculty during class."
    },
    {
      "heading": "Direct Support Channel",
      "text": "Request to initiate a chat with your faculty when you need assistance or have questions."
    },
    {
      "heading": "Transparent Attendance Records",
      "text": "View your attendance history for each class you are enrolled in."
    },
    {
      "heading": "Convenient Content Access",
      "text": "Access all class materials and resources uploaded by your faculty in a single, organized place."
    },
    {
      "heading": "Clear Routine Overview",
      "text": "Stay informed about your class schedules and routines directly within the application."
    }
  ]

const AboutPage = () => {
    const featureClass = 'font-semibold text-[#63c377]'
  return (
    <div className="md:py-10 md:px-[6vw] px-4 py-6">
        <h1 className="md:text-5xl text-3xl text-center  logo">About</h1>
        <p className="text-sm mt-12">Welcome to <span className="logo text-lg">Classync</span>, a comprehensive and intuitive platform designed to revolutionize the way educators and students connect, collaborate, and succeed. Our mission is to streamline classroom management, enhance communication, and provide easy access to learning resources, fostering a more engaging and effective educational experience for everyone.</p>
        <p className="text-sm mt-4">In today&apos;s dynamic educational landscape, we understand the challenges faced by both faculty and students in managing coursework, communication, and participation. [Your Classroom Management Tool Name] was built to address these needs by providing a centralized hub for all classroom activities.</p>
        <h3 className="text-center logo text-3xl mt-10">What we offer</h3>
        <div>

        <h4 className="text-xl mt-8">For Faculty</h4>
        <div className="flex flex-col gap-2 mt-4">
        {
            facultyFeatures.map((f, idx)=><p key={idx}><span className={featureClass}>{f.heading}</span> {f.text}</p>)
        }
        </div>
        </div>
        <div>

        <h4 className="text-xl mt-8">For Students</h4>
        <div className="flex flex-col gap-2 mt-4">
        {
            studentFeatures.map((f, idx)=><p key={idx}><span className={featureClass}>{f.heading}:</span> {f.text}</p>)
        }
        </div>
        </div>
    </div>
  )
}

export default AboutPage