import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
// import localLogo from "next/font/local"

// const fontLogo = localLogo({
//   src:"../assets/fonts/logo.ttf"
// })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={``}
        cz-shortcut-listen="true"
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
